// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetMyPublicKey() {
  return window['go']['main']['App']['GetMyPublicKey']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SignFile(arg1) {
  return window['go']['main']['App']['SignFile'](arg1);
}
