// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetMyPublicKey():Promise<string>;

export function Login(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SignFile(arg1:string):Promise<string>;
