// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetMyPublicKey() {
  return window['go']['main']['App']['GetMyPublicKey']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SignFile(arg1) {
  return window['go']['main']['App']['SignFile'](arg1);
}

export function VerifySignature(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifySignature'](arg1, arg2, arg3);
}
