// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keyring} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteContact(arg1:string):Promise<void>;

export function GetContacts():Promise<Array<keyring.Contact>>;

export function GetMyPublicKey():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string):Promise<void>;

export function Logout():Promise<void>;

export function SelectFile():Promise<string>;

export function SignFile(arg1:string):Promise<string>;
